apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: nginx-analysis
  namespace: default
spec:
  args:
  - name: service-name
  metrics:
  - name: nginx-up
    interval: 30s
    count: 3
    successCondition: result[0] >= 1
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          nginx_up{job="nginx-exporter"}
  - name: connection-rate
    interval: 30s
    count: 3
    successCondition: result[0] >= 0
    # failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          ratex(nginx_connections_accepted[1m])
  - name: request-rate
    interval: 30s
    count: 3
    successCondition: result[0] >= 0
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          rate(nginx_http_requests_total[1m])