apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kube-test
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      containers:
      - name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "25m"
            memory: "70Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
